# Generated by Django 3.2.14 on 2022-07-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('published', models.BooleanField()),
                ('title', models.CharField(max_length=200)),
                ('into', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
    ]
