# Generated by Django 3.2.14 on 2022-07-05 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_posts_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='into',
            new_name='intro',
        ),
    ]
